# Generated by Django 5.2.4 on 2025-08-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(help_text='Write a description about the status:', max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='newfield'),
            preserve_default=False,
        ),
    ]
