# Generated by Django 5.2.4 on 2025-08-15 01:17

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries ={
        "published":"A post available for all to view",
        "draft":"A post only visible to the author",
        "archived":"An older post visible only to logged user"
    }
    Status = apps.get_model("posts","Status")
    for key, value in entries.items():
        status__obj = Status(name=key, description=value)
        status__obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status_post_body'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
